### ISSUE TITLE
Inclusion request: clecs

### ISSUE THREAD

**Issue by muhuk** [weavejester/clojure-toolbox.com#106]
Entity-component-system for Clojure.
```yaml
brute:
  name: clecs
  url: https://github.com/muhuk/clecs
  category: Game Development
```
