### ISSUE TITLE
Add libraries to the toolbox

### ISSUE THREAD

**Issue by greglook** [weavejester/clojure-toolbox.com#65]
Hello, and thanks for setting up this webpage! It's been helpful both to me and to point people at when they say they don't know of any Clojure libraries. I'd like to get some of my projects added to the toolbox.

Rather than open a pull request for a few four-line additions, it seems easier to just drop some code blocks here, but if you'd prefer I can fork and turn this into a pull request. Also, feel free to suggest better categories for any of these.
### [Puget](https://github.com/greglook/puget)

A library for canonical colorized EDN printing, using FIPP. Not sure what the best category here is, I went with CLI and Serialization.

``` yaml
puget:
  name: Puget
  url: https://github.com/greglook/puget
  category: Command line tools, Serialization
```

I also wrote [lein-cprint](https://github.com/greglook/lein-cprint), which is just like `lein-pprint` but with colored output. I don't know if that's worth a spot in the toolbox.
### [lein-hiera](https://github.com/greglook/lein-hiera)

A Leiningen plugin to generate namespace hierarchy graphs. Uses Graphviz via Rhizome.

``` yaml
lein-hiera:
  name: lein-hiera
  url: https://github.com/greglook/lein-hiera
  category: Code Analysis
```
### [clj-pgp](https://github.com/greglook/clj-pgp)

Wraps the Bouncy Castle OpenPGP library with a nice Clojure interface.

``` yaml
clj-pgp:
  name: clj-pgp
  url: https://github.com/greglook/clj-pgp
  category: Cryptography
```
